/**
 * SPDX-License-Identifier: MIT
 */

import { join } from 'node:path';
import type {
  AppliedFileChange,
  EnvVarSpec,
  PlannedFileChange,
  ProjectProfileAttributes,
  SetupPlanAttributes,
} from './schemas.js';

export interface GeneratePlanOptions {
  rootDir: string;
  sessionId: string;
  profileId: string;
  profile: ProjectProfileAttributes;
}

export const PRISMA_SCHEMA_PATH = 'packages/database/prisma/schema.prisma';

function buildSingleTenantSchema(primaryEntity: string): string {
  const normalizedEntity =
    primaryEntity.trim().length > 0 ? primaryEntity.trim() : 'project';

  return `// Prisma schema generated by Zopio project setup
// Template: single-tenant
// Primary domain entity: ${normalizedEntity}

generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["driverAdapters"]
  output          = "../generated/client"
}

datasource db {
  provider     = "postgresql"
  url          = env("DATABASE_URL")
  relationMode = "prisma"
}

model User {
  id        String   @id @default(cuid())
  email     String   @unique
  name      String?
  projects  Project[]
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
}

model Project {
  id          String   @id @default(cuid())
  name        String
  description String?
  ownerId     String
  owner       User     @relation(fields: [ownerId], references: [id])
  createdAt   DateTime @default(now())
  updatedAt   DateTime @updatedAt

  @@index([ownerId])
}
`;
}

function buildMultiTenantSchema(primaryEntity: string): string {
  const normalizedEntity =
    primaryEntity.trim().length > 0 ? primaryEntity.trim() : 'organization';

  return `// Prisma schema generated by Zopio project setup
// Template: multi-tenant
// Primary domain entity: ${normalizedEntity}

generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["driverAdapters"]
  output          = "../generated/client"
}

datasource db {
  provider     = "postgresql"
  url          = env("DATABASE_URL")
  relationMode = "prisma"
}

model User {
  id           String       @id @default(cuid())
  email        String       @unique
  name         String?
  memberships  Membership[]
  createdAt    DateTime     @default(now())
  updatedAt    DateTime     @updatedAt
}

model Organization {
  id           String       @id @default(cuid())
  name         String
  slug         String       @unique
  memberships  Membership[]
  createdAt    DateTime     @default(now())
  updatedAt    DateTime     @updatedAt
}

model Membership {
  id             String        @id @default(cuid())
  userId         String
  organizationId String
  role           String        @default("member")
  user           User          @relation(fields: [userId], references: [id])
  organization   Organization  @relation(fields: [organizationId], references: [id])
  createdAt      DateTime      @default(now())
  updatedAt      DateTime      @updatedAt

  @@unique([userId, organizationId])
  @@index([organizationId])
}
`;
}

function baseEnvVars(): EnvVarSpec[] {
  return [
    {
      name: 'DATABASE_URL',
      value: '""',
      comment: 'PostgreSQL connection string',
    },
  ];
}

function authEnvVars(): EnvVarSpec[] {
  return [
    {
      name: 'CLERK_SECRET_KEY',
      value: '""',
      comment: 'Clerk secret key (server-side)',
    },
    {
      name: 'CLERK_WEBHOOK_SECRET',
      value: '""',
      comment: 'Clerk webhook secret (optional)',
    },
    {
      name: 'NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY',
      value: '""',
      comment: 'Clerk publishable key (client-side)',
    },
  ];
}

function observabilityEnvVars(): EnvVarSpec[] {
  return [
    {
      name: 'BETTERSTACK_API_KEY',
      value: '""',
      comment: 'BetterStack logging API key (optional)',
    },
    {
      name: 'BETTERSTACK_URL',
      value: '""',
      comment: 'BetterStack logging endpoint (optional)',
    },
    {
      name: 'SENTRY_ORG',
      value: '""',
      comment: 'Sentry organization slug (optional)',
    },
    {
      name: 'SENTRY_PROJECT',
      value: '""',
      comment: 'Sentry project slug (optional)',
    },
    {
      name: 'NEXT_PUBLIC_SENTRY_DSN',
      value: '""',
      comment: 'Sentry DSN for client-side error tracking (optional)',
    },
  ];
}

function analyticsEnvVars(): EnvVarSpec[] {
  return [
    {
      name: 'NEXT_PUBLIC_POSTHOG_KEY',
      value: '""',
      comment: 'PostHog client key (phc_...)',
    },
    {
      name: 'NEXT_PUBLIC_POSTHOG_HOST',
      value: '""',
      comment: 'PostHog API host (https://app.posthog.com or self-hosted URL)',
    },
    {
      name: 'NEXT_PUBLIC_GA_MEASUREMENT_ID',
      value: '""',
      comment: 'Google Analytics measurement ID (optional)',
    },
  ];
}

function storageEnvVars(): EnvVarSpec[] {
  return [
    {
      name: 'BLOB_READ_WRITE_TOKEN',
      value: '""',
      comment: 'Vercel Blob read/write token (optional)',
    },
  ];
}

function rateLimitEnvVars(): EnvVarSpec[] {
  return [
    {
      name: 'UPSTASH_REDIS_REST_URL',
      value: '""',
      comment: 'Upstash Redis REST URL for rate limiting (optional)',
    },
    {
      name: 'UPSTASH_REDIS_REST_TOKEN',
      value: '""',
      comment: 'Upstash Redis REST token (optional)',
    },
  ];
}

// biome-ignore lint/complexity/noExcessiveCognitiveComplexity: setup plan generation is intentionally centralized
export function generateSetupPlanAttributes(
  options: GeneratePlanOptions
): SetupPlanAttributes {
  const { sessionId, profileId, profile } = options;

  const prismaTemplate =
    profile.architecture === 'multi_tenant' ? 'multi_tenant' : 'single_tenant';

  const prismaContent =
    prismaTemplate === 'multi_tenant'
      ? buildMultiTenantSchema(profile.primaryEntity)
      : buildSingleTenantSchema(profile.primaryEntity);

  const fileChanges: PlannedFileChange[] = [];

  // Prisma schema
  fileChanges.push({
    path: PRISMA_SCHEMA_PATH,
    type: 'update',
    description:
      'Replace stub Prisma schema with a multi-tenant-ready template',
    operation: 'overwrite',
    content: prismaContent,
  });

  // Database env template
  fileChanges.push({
    path: 'packages/database/.env.example',
    type: 'update',
    description: 'Ensure DATABASE_URL is documented for the database package',
    operation: 'merge_env',
    envVars: baseEnvVars(),
  });

  // Storage package env template
  if (profile.storageLevel === 'basic') {
    fileChanges.push({
      path: 'packages/storage/.env.example',
      type: 'create',
      description:
        'Add environment template for Vercel Blob storage configuration',
      operation: 'merge_env',
      envVars: storageEnvVars(),
    });
  }

  const needsAuth = profile.authMode !== 'none';
  const needsAnalytics = profile.analyticsLevel !== 'none';
  const needsObservability =
    profile.observabilityLevel === 'standard' ||
    profile.observabilityLevel === 'extended';
  const needsRateLimiting = profile.rateLimitingLevel === 'basic';
  const needsStorage = profile.storageLevel === 'basic';

  const envRelatedApps: Array<{ app: 'app' | 'api' | 'web'; path: string }> =
    [];

  if (profile.apps.includes('app')) {
    envRelatedApps.push({ app: 'app', path: 'apps/app/.env.example' });
  }
  if (profile.apps.includes('api')) {
    envRelatedApps.push({ app: 'api', path: 'apps/api/.env.example' });
  }
  if (profile.apps.includes('web')) {
    envRelatedApps.push({ app: 'web', path: 'apps/web/.env.example' });
  }

  for (const { app, path } of envRelatedApps) {
    const envVars: EnvVarSpec[] = [];

    envVars.push(...baseEnvVars());

    if (needsAuth && (app === 'app' || app === 'api')) {
      envVars.push(...authEnvVars());
    }

    if (needsObservability) {
      envVars.push(...observabilityEnvVars());
    }

    if (needsAnalytics && (app === 'app' || app === 'web')) {
      envVars.push(...analyticsEnvVars());
    }

    if (needsStorage && (app === 'app' || app === 'api')) {
      envVars.push(...storageEnvVars());
    }

    if (needsRateLimiting && app === 'api') {
      envVars.push(...rateLimitEnvVars());
    }

    fileChanges.push({
      path,
      type: 'update',
      description: `Ensure required environment variables are present for ${path}`,
      operation: 'merge_env',
      envVars,
    });
  }

  // Example storage route (only if API app is selected and storage is needed)
  if (profile.apps.includes('api') && needsStorage) {
    fileChanges.push({
      path: 'apps/api/app/storage/example-upload/route.ts',
      type: 'create',
      description:
        'Add example route demonstrating basic Vercel Blob storage usage',
      operation: 'create_if_missing',
      content: `/**
 * SPDX-License-Identifier: MIT
 */

import { put } from '@repo/storage';

export async function POST(): Promise<Response> {
  try {
    // This route is a minimal example of using Vercel Blob through @repo/storage.
    // It does not accept arbitrary user input and only writes a small placeholder file.
    const blob = await put('example.txt', 'Hello from Zopio storage example', {
      access: 'private'
    });

    return new Response(
      JSON.stringify({
        ok: true,
        url: blob.url,
        note:
          'This is a placeholder route. Replace with real upload logic for your project.'
      }),
      {
        status: 200,
        headers: {
          'content-type': 'application/json'
        }
      }
    );
  } catch (error) {
    return new Response(
      JSON.stringify({
        ok: false,
        error:
          'Failed to write to storage. Check BLOB_READ_WRITE_TOKEN and Vercel Blob configuration.'
      }),
      {
        status: 500,
        headers: {
          'content-type': 'application/json'
        }
      }
    );
  }
}
`,
    });
  }

  // Example rate-limited route (API app and rate limiting enabled)
  if (profile.apps.includes('api') && needsRateLimiting) {
    fileChanges.push({
      path: 'apps/api/app/rate-limited/ping/route.ts',
      type: 'create',
      description:
        'Add example route demonstrating basic Upstash-based rate limiting',
      operation: 'create_if_missing',
      content: `/**
 * SPDX-License-Identifier: MIT
 */

import { createRateLimiter, slidingWindow } from '@repo/rate-limit';

export async function GET(): Promise<Response> {
  const hasUpstashConfig =
    !!process.env.UPSTASH_REDIS_REST_URL &&
    !!process.env.UPSTASH_REDIS_REST_TOKEN;

  if (!hasUpstashConfig) {
    return new Response(
      JSON.stringify({
        ok: true,
        rateLimited: false,
        message:
          'Rate limiting example route. Configure UPSTASH_REDIS_REST_URL and UPSTASH_REDIS_REST_TOKEN to enable real limiting.'
      }),
      {
        status: 200,
        headers: {
          'content-type': 'application/json'
        }
      }
    );
  }

  const limiter = createRateLimiter({
    limiter: slidingWindow(10, '10 s'),
    prefix: 'zopio_rate_example'
  });

  const ip = 'anonymous';
  const { success, limit, remaining, reset } = await limiter.limit(
    \`ping_\${ip}\`
  );

  if (!success) {
    return new Response(
      JSON.stringify({
        ok: false,
        rateLimited: true,
        message: 'Too many requests. Please try again later.'
      }),
      {
        status: 429,
        headers: {
          'content-type': 'application/json',
          'retry-after': reset.toString()
        }
      }
    );
  }

  return new Response(
    JSON.stringify({
      ok: true,
      rateLimited: false,
      limit,
      remaining,
      reset
    }),
    {
      status: 200,
      headers: {
        'content-type': 'application/json'
      }
    }
  );
}
`,
    });
  }

  const summary = `Setup plan for ${profile.architecture.replace(
    '_',
    '-'
  )} project using apps: ${profile.apps.join(', ')}`;

  return {
    sessionId,
    profileId,
    summary,
    apps: profile.apps,
    prisma: {
      schemaPath: PRISMA_SCHEMA_PATH,
      template: prismaTemplate,
      primaryEntity: profile.primaryEntity,
    },
    fileChanges,
  };
}

export interface ApplyFileChangeResult extends AppliedFileChange {}

export interface ApplyPlanOptions {
  rootDir: string;
  changes: PlannedFileChange[];
}

export function resolvePath(rootDir: string, relativePath: string): string {
  return join(rootDir, relativePath);
}
