packages:
  - packages/*
  - packages/core/*
  - packages/data/*
  - packages/addons/*
  - apps/*

onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@clerk/shared'
  - '@prisma/client'
  - '@prisma/engines'
  - '@sentry/cli'
  - '@tailwindcss/oxide'
  - bufferutil
  - core-js
  - core-js-pure
  - esbuild
  - msgpackr-extract
  - prisma
  - sharp
