packages:
  - apps/*
  - devapps/*
  - packages/*
  - registry/*
  - websites/*
onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@clerk/shared'
  - '@parcel/watcher'
  - '@prisma/client'
  - '@prisma/engines'
  - '@sentry/cli'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - bufferutil
  - core-js
  - core-js-pure
  - esbuild
  - prisma
  - protobufjs
  - sharp
