/**
 * SPDX-License-Identifier: MIT
 */

import type { ProjectProfile } from '../schemas/profile.js';
import { TenancyModel } from '../schemas/profile.js';

/**
 * Capitalize first letter of a string
 */
function capitalize(str: string): string {
  return str.charAt(0).toUpperCase() + str.slice(1);
}

/**
 * Convert snake_case to PascalCase for model names
 */
function toPascalCase(str: string): string {
  return str
    .split('_')
    .map((word) => capitalize(word))
    .join('');
}

/**
 * Generate the base Prisma schema header
 */
function generateSchemaHeader(): string {
  return `// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema
// Generated by Zopio Project Setup MCP

generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["driverAdapters"]
  output          = "../generated/client"
}

datasource db {
  provider     = "postgresql"
  url          = env("DATABASE_URL")
  relationMode = "prisma"
}
`;
}

/**
 * Generate User model
 */
function generateUserModel(hasRoles: boolean): string {
  const roleField = hasRoles
    ? '\n  role          String    @default("member")'
    : '';

  return `
// User model - synced with Clerk
model User {
  id            String    @id @default(cuid())
  clerkId       String    @unique
  email         String    @unique
  name          String?
  imageUrl      String?${roleField}
  createdAt     DateTime  @default(now())
  updatedAt     DateTime  @updatedAt

  memberships   Membership[]

  @@index([clerkId])
  @@index([email])
}
`;
}

/**
 * Generate Organization/Primary Entity model for multi-tenant
 */
function generateOrganizationModel(entityName: string): string {
  const modelName = toPascalCase(entityName);
  const tableName = entityName.toLowerCase();

  return `
// ${modelName} model - primary business entity
model ${modelName} {
  id            String    @id @default(cuid())
  name          String
  slug          String    @unique
  description   String?
  imageUrl      String?
  createdAt     DateTime  @default(now())
  updatedAt     DateTime  @updatedAt

  memberships   Membership[]

  @@map("${tableName}")
  @@index([slug])
}
`;
}

/**
 * Generate Membership model for multi-tenant (joins users to organizations)
 */
function generateMembershipModel(
  entityName: string,
  hasRoles: boolean
): string {
  const orgModelName = toPascalCase(entityName);
  const orgIdField = `${entityName}Id`;
  const roleField = hasRoles
    ? '\n  role          String    @default("member")'
    : '';

  return `
// Membership model - links users to ${entityName}s
model Membership {
  id            String    @id @default(cuid())
  userId        String
  ${orgIdField}    String${roleField}
  createdAt     DateTime  @default(now())
  updatedAt     DateTime  @updatedAt

  user          User      @relation(fields: [userId], references: [id], onDelete: Cascade)
  ${entityName}    ${orgModelName}  @relation(fields: [${orgIdField}], references: [id], onDelete: Cascade)

  @@unique([userId, ${orgIdField}])
  @@index([userId])
  @@index([${orgIdField}])
}
`;
}

/**
 * Generate a simple User model for single-tenant
 */
function generateSimpleUserModel(hasRoles: boolean): string {
  const roleField = hasRoles
    ? '\n  role          String    @default("user")'
    : '';

  return `
// User model - synced with Clerk
model User {
  id            String    @id @default(cuid())
  clerkId       String    @unique
  email         String    @unique
  name          String?
  imageUrl      String?${roleField}
  createdAt     DateTime  @default(now())
  updatedAt     DateTime  @updatedAt

  @@index([clerkId])
  @@index([email])
}
`;
}

/**
 * Generate complete Prisma schema based on project profile
 */
export function generatePrismaSchema(profile: ProjectProfile): string {
  const parts: string[] = [generateSchemaHeader()];
  const { tenancyModel, primaryEntity } = profile.architecture;
  const hasRoles = profile.crossCuttingConcerns.auth.requiresRoles;

  if (tenancyModel === TenancyModel.MULTI_TENANT) {
    parts.push(generateUserModel(hasRoles));
    parts.push(generateOrganizationModel(primaryEntity));
    parts.push(generateMembershipModel(primaryEntity, hasRoles));
  } else {
    parts.push(generateSimpleUserModel(hasRoles));
  }

  return parts.join('\n');
}

/**
 * Get a description of what the schema will contain
 */
export function describePrismaSchema(profile: ProjectProfile): string {
  const { tenancyModel, primaryEntity } = profile.architecture;
  const hasRoles = profile.crossCuttingConcerns.auth.requiresRoles;

  if (tenancyModel === TenancyModel.MULTI_TENANT) {
    const models = ['User', toPascalCase(primaryEntity), 'Membership'];
    const features = hasRoles ? ' with role-based access' : '';
    return `Multi-tenant schema with models: ${models.join(', ')}${features}`;
  }

  const features = hasRoles ? ' with role field' : '';
  return `Single-tenant schema with User model${features}`;
}
