/**
 * SPDX-License-Identifier: MIT
 */

import type { ProjectProfile } from '../schemas/profile.js';

/**
 * Generate rate limiting middleware snippet for API routes
 * Uses the existing @repo/rate-limit package pattern
 */
export function generateRateLimitMiddleware(): string {
  return `/**
 * SPDX-License-Identifier: MIT
 *
 * Rate limiting utilities using @repo/rate-limit
 * Generated by Zopio Project Setup MCP
 */

import { createRateLimiter, slidingWindow } from '@repo/rate-limit';
import { NextResponse } from 'next/server';
import type { NextRequest } from 'next/server';

// Create rate limiters for different use cases
// TODO: Adjust limits based on your requirements

/**
 * Default API rate limiter
 * 10 requests per 10 seconds per IP
 */
export const apiRateLimiter = createRateLimiter({
  limiter: slidingWindow(10, '10 s'),
  prefix: 'api',
});

/**
 * Strict rate limiter for sensitive endpoints
 * 5 requests per minute per IP
 */
export const strictRateLimiter = createRateLimiter({
  limiter: slidingWindow(5, '60 s'),
  prefix: 'api-strict',
});

/**
 * Rate limiting middleware wrapper for API routes
 *
 * Usage in route handler:
 * \`\`\`ts
 * import { withRateLimit, apiRateLimiter } from '@/lib/rate-limit';
 *
 * export const GET = withRateLimit(apiRateLimiter, async (request) => {
 *   // Your handler logic
 *   return NextResponse.json({ data: 'Hello' });
 * });
 * \`\`\`
 */
export function withRateLimit(
  rateLimiter: ReturnType<typeof createRateLimiter>,
  handler: (request: NextRequest) => Promise<Response>
) {
  return async (request: NextRequest): Promise<Response> => {
    const ip = request.headers.get('x-forwarded-for') ?? '127.0.0.1';
    const { success, limit, reset, remaining } = await rateLimiter.limit(ip);

    if (!success) {
      return NextResponse.json(
        { error: 'Too many requests', retryAfter: Math.ceil((reset - Date.now()) / 1000) },
        {
          status: 429,
          headers: {
            'X-RateLimit-Limit': limit.toString(),
            'X-RateLimit-Remaining': remaining.toString(),
            'X-RateLimit-Reset': reset.toString(),
            'Retry-After': Math.ceil((reset - Date.now()) / 1000).toString(),
          },
        }
      );
    }

    const response = await handler(request);

    // Add rate limit headers to response
    const headers = new Headers(response.headers);
    headers.set('X-RateLimit-Limit', limit.toString());
    headers.set('X-RateLimit-Remaining', remaining.toString());
    headers.set('X-RateLimit-Reset', reset.toString());

    return new Response(response.body, {
      status: response.status,
      statusText: response.statusText,
      headers,
    });
  };
}
`;
}

/**
 * Generate storage utility snippet
 */
export function generateStorageUtil(): string {
  return `/**
 * SPDX-License-Identifier: MIT
 *
 * Storage utilities using Vercel Blob
 * Generated by Zopio Project Setup MCP
 */

import { put, del, list, head } from '@vercel/blob';

// TODO: Configure allowed file types and size limits for your use case
const ALLOWED_TYPES = ['image/jpeg', 'image/png', 'image/webp', 'application/pdf'];
const MAX_SIZE_MB = 10;

/**
 * Upload a file to Vercel Blob storage
 *
 * @param file - File to upload
 * @param options - Upload options
 * @returns Upload result with URL
 */
export async function uploadFile(
  file: File,
  options?: {
    folder?: string;
    access?: 'public' | 'private';
  }
) {
  // Validate file type
  if (!ALLOWED_TYPES.includes(file.type)) {
    throw new Error(\`File type \${file.type} is not allowed\`);
  }

  // Validate file size
  const sizeMB = file.size / (1024 * 1024);
  if (sizeMB > MAX_SIZE_MB) {
    throw new Error(\`File size exceeds \${MAX_SIZE_MB}MB limit\`);
  }

  const folder = options?.folder ?? 'uploads';
  const pathname = \`\${folder}/\${Date.now()}-\${file.name}\`;

  const blob = await put(pathname, file, {
    access: options?.access ?? 'public',
  });

  return {
    url: blob.url,
    pathname: blob.pathname,
    contentType: blob.contentType,
  };
}

/**
 * Delete a file from Vercel Blob storage
 *
 * @param url - Blob URL to delete
 */
export async function deleteFile(url: string): Promise<void> {
  await del(url);
}

/**
 * List files in Vercel Blob storage
 *
 * @param options - List options
 * @returns List of blobs
 */
export async function listFiles(options?: { prefix?: string; limit?: number }) {
  const result = await list({
    prefix: options?.prefix,
    limit: options?.limit ?? 100,
  });

  return result.blobs;
}

/**
 * Get file metadata
 *
 * @param url - Blob URL
 * @returns Blob metadata
 */
export async function getFileInfo(url: string) {
  return head(url);
}
`;
}

/**
 * Generate PostHog identifier component (matches actual Zopio pattern)
 */
export function generateAnalyticsProvider(profile: ProjectProfile): string {
  const { analytics } = profile.crossCuttingConcerns;

  if (!analytics.posthog) {
    return `/**
 * SPDX-License-Identifier: MIT
 *
 * Analytics identifier component
 * Generated by Zopio Project Setup MCP
 *
 * PostHog is not enabled. Enable it in project setup to use analytics.
 */

export const AnalyticsIdentifier = () => null;
`;
  }

  return `/**
 * SPDX-License-Identifier: MIT
 *
 * PostHog analytics identifier component
 * Generated by Zopio Project Setup MCP
 *
 * This component identifies users and tracks pageviews in PostHog.
 * Add it to your authenticated layout.
 */

'use client';

import { useAnalytics } from '@repo/analytics/posthog/client';
import { useUser } from '@repo/auth/client';
import { usePathname, useSearchParams } from 'next/navigation';
import { useEffect, useRef } from 'react';

export const PostHogIdentifier = () => {
  const { user } = useUser();
  const identified = useRef(false);
  const pathname = usePathname();
  const searchParams = useSearchParams();
  const analytics = useAnalytics();

  useEffect(() => {
    // Track pageviews
    if (pathname && analytics) {
      try {
        let url = window.origin + pathname;
        if (searchParams.toString()) {
          url = \`\${url}?\${searchParams.toString()}\`;
        }
        analytics.capture('$pageview', {
          $current_url: url,
        });
      } catch (_error) {
        // Silently handle analytics errors
      }
    }
  }, [pathname, searchParams, analytics]);

  useEffect(() => {
    if (!user || identified.current || !analytics) {
      return;
    }

    try {
      analytics.identify(user.id, {
        email: user.emailAddresses.at(0)?.emailAddress,
        firstName: user.firstName,
        lastName: user.lastName,
        createdAt: user.createdAt,
        avatar: user.imageUrl,
        phoneNumber: user.phoneNumbers.at(0)?.phoneNumber,
      });

      identified.current = true;
    } catch (_error) {
      // Silently handle analytics errors
    }
  }, [user, analytics]);

  return null;
};

// TODO: Add <PostHogIdentifier /> to your authenticated layout
`;
}

/**
 * Generate instrumentation.ts file for Sentry initialization
 * Matches the actual Zopio pattern
 */
export function generateInstrumentation(): string {
  return `/**
 * SPDX-License-Identifier: MIT
 *
 * Instrumentation file for Sentry initialization
 * Generated by Zopio Project Setup MCP
 *
 * This file initializes Sentry for error tracking and performance monitoring.
 * It is automatically loaded by Next.js.
 */

import { initializeSentry } from '@repo/observability/instrumentation';

export const register = initializeSentry();
`;
}

/**
 * Generate a database seed script template
 */
export function generateDatabaseSeed(profile: ProjectProfile): string {
  const { architecture, crossCuttingConcerns } = profile;
  const entityName = architecture.primaryEntity;
  const capitalizedEntity =
    entityName.charAt(0).toUpperCase() + entityName.slice(1);
  const hasRoles = crossCuttingConcerns.auth.requiresRoles;

  return `/**
 * SPDX-License-Identifier: MIT
 *
 * Database seed script
 * Generated by Zopio Project Setup MCP
 *
 * Usage:
 *   npx tsx packages/database/seed.ts
 *
 * This script creates initial test data for development.
 */

import { PrismaClient } from './generated/client';

const prisma = new PrismaClient();

async function seed() {
  console.log('🌱 Starting database seed...');

  // Create a test user
  const user = await prisma.user.upsert({
    where: { email: 'test@example.com' },
    update: {},
    create: {
      clerkId: 'user_test_123',
      email: 'test@example.com',
      name: 'Test User',${hasRoles ? "\n      role: 'admin'," : ''}
    },
  });
  console.log('✅ Created test user:', user.email);

  // Create a test ${entityName}
  const ${entityName} = await prisma.${entityName}.upsert({
    where: { slug: 'test-${entityName}' },
    update: {},
    create: {
      name: 'Test ${capitalizedEntity}',
      slug: 'test-${entityName}',
      description: 'A test ${entityName} for development',
    },
  });
  console.log('✅ Created test ${entityName}:', ${entityName}.slug);

  // Create membership linking user to ${entityName}
  await prisma.membership.upsert({
    where: {
      userId_${entityName}Id: {
        userId: user.id,
        ${entityName}Id: ${entityName}.id,
      },
    },
    update: {},
    create: {
      userId: user.id,
      ${entityName}Id: ${entityName}.id,${hasRoles ? "\n      role: 'admin'," : ''}
    },
  });
  console.log('✅ Created membership for user in ${entityName}');

  console.log('\\n🎉 Database seed completed!');
}

seed()
  .catch((error) => {
    console.error('❌ Seed failed:', error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
`;
}

/**
 * Generate a basic PROJECT_SETUP.md summary file
 */
export function generateSetupSummaryDoc(profile: ProjectProfile): string {
  const { metadata, selectedApps, architecture, crossCuttingConcerns } =
    profile;

  const apps = Object.entries(selectedApps)
    .filter(([, enabled]) => enabled)
    .map(([name]) => `apps/${name}`)
    .join(', ');

  const features: string[] = [];
  if (crossCuttingConcerns.auth.enabled) {
    features.push('Authentication (Clerk)');
  }
  if (crossCuttingConcerns.observability.enabled) {
    features.push('Observability (Sentry/Logtail)');
  }
  if (crossCuttingConcerns.analytics.enabled) {
    features.push('Analytics');
  }
  if (crossCuttingConcerns.storage.enabled) {
    features.push('Storage (Vercel Blob)');
  }
  if (crossCuttingConcerns.rateLimit.enabled) {
    features.push('Rate Limiting (Upstash)');
  }

  return `# Project Setup Summary

This project was bootstrapped using the Zopio Project Setup MCP.

## Project Information

- **Name**: ${metadata.name}
- **Description**: ${metadata.description || 'N/A'}
- **Target Users**: ${metadata.targetUsers}

## Architecture

- **Tenancy Model**: ${architecture.tenancyModel}
- **Primary Entity**: ${architecture.primaryEntity}

## Selected Apps

${apps}

## Enabled Features

${features.map((f) => `- ${f}`).join('\n')}

## Next Steps

1. Configure environment variables in each app's \`.env.local\` file
2. Run \`pnpm migrate\` to set up the database schema
3. Review and customize the generated wiring code
4. Start development with \`pnpm dev\`

## Environment Variables

Make sure to set up the following required environment variables:

- \`DATABASE_URL\`: Neon PostgreSQL connection string
${crossCuttingConcerns.auth.enabled ? '- `CLERK_SECRET_KEY`: Clerk secret key\n- `NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY`: Clerk publishable key' : ''}
${crossCuttingConcerns.observability.enabled ? '- `NEXT_PUBLIC_SENTRY_DSN`: Sentry DSN' : ''}
${crossCuttingConcerns.analytics.posthog ? '- `NEXT_PUBLIC_POSTHOG_KEY`: PostHog API key\n- `NEXT_PUBLIC_POSTHOG_HOST`: PostHog host' : ''}
${crossCuttingConcerns.storage.enabled ? '- `BLOB_READ_WRITE_TOKEN`: Vercel Blob token' : ''}
${crossCuttingConcerns.rateLimit.enabled ? '- `UPSTASH_REDIS_REST_URL`: Upstash Redis URL\n- `UPSTASH_REDIS_REST_TOKEN`: Upstash Redis token' : ''}

---
Generated on: ${new Date().toISOString()}
`;
}
